### ISSUE TITLE
Silents Mechanisms Canister causing crash while viewing recipes in JEI

### ISSUE THREAD

**Issue by Drakma** [SilentChaos512/Silents-Mechanisms#140] opened 2021-04-12 05:04 UTC
## Versions

- **Silent's Mechanisms**: 1.16.3-0.8.9+74
- **Silent Lib**: 1.16.3-4.9.6
- **Forge**: 36.1.4
- **Modpack**: N/A

## Expected Behavior

Ability to view canister recipes in JEI
## Actual Behavior

Locks up as soon as a canister is in view in JEI

## Links/Images

Already reported to JEI team : https://github.com/mezz/JustEnoughItems/issues/2307
My crash report: https://gist.github.com/Drakma/2d47cb602ed219bb555d488d7726bd45
## Steps to Reproduce the Problem

1. Scroll through JEI/search for "canister"
2.
3.

**Comment by magcicada** [comment] 2021-04-12 11:51
The same issue for me,the game will crash when I open the page of Silents Mechanisms in JEI.
[CR](https://gist.githubusercontent.com/natanfudge/24200f5755dae36c2b4e17aa8249d706/raw/43f6234e76866f9f4ae38ba174be2d9bcb6648bb/crash.txt)

**Comment by magcicada** [comment] 2021-04-12 12:11
The new version resolved this issue,the curseforge client can't find and download the new version mod file.......

**Comment by SilentChaos512** [comment] 2021-04-12 23:07
Duplicate of #139, was fixed in version 1.0.1.

**Closed as completed by SilentChaos512** 2021-04-12 23:07 UTC
Labels: bug
