### ISSUE TITLE
Blaze Rods can be duplicated using compressor

### ISSUE THREAD

**Issue by BetaCarotina** [SilentChaos512/Silents-Mechanisms#78] opened 2020-04-29 18:47 UTC
Compressor only needs 2 Blaze Powders for a single Blaze Rod, which is allows it to be duplicated, since even Crusher can pulverize Blaze Rod into 4 powder. Compressor should use 5 powders, like other mods.

**Comment by SilentChaos512** [comment] 2020-05-05 12:28
Duplicate of #64, will get this fixed today.

**Closed as completed by SilentChaos512** 2020-05-05 12:28 UTC
Labels: bug, duplicate
