### ISSUE TITLE
Infuser missing texture

### ISSUE THREAD

**Issue by ChromaPIE** [SilentChaos512/Silents-Mechanisms#135] opened 2021-02-25 08:00 UTC
## Versions

- **Silent's Mechanisms**: 1.16.3-0.8.10+75
- **Silent Lib**: 1.16.3-4.9.1+64
- **Forge**: 36.0.42
- **Modpack**: N/A

## Expected Behavior

- Correctly shown texture for the Infuser

## Actual Behavior

- The Infuser showing a missing texture.

**Comment by SilentChaos512** [comment] 2021-02-25 17:02
Duplicate of #121

**Closed as completed by SilentChaos512** 2021-02-25 17:02 UTC
Labels: bug
